### ISSUE TITLE
3.5.4 Beta2: Löschen mehrerer Sicherungen kein Status

### ISSUE THREAD

**Issue by linuxcrash** [alexsee/bsh3#19]
Wenn mit dem Backupbrowser mehrere Sicherungen gelöscht werden (3-30) dann wird kein Status angezeigt und der Benutzer hat keine Ahnung wie weit BSH schon ist und wie langes es ungefähr noch dauern kann. Es währe schön zu sehen wie viele Dateien noch ausstehend sind und bestenfalls sogar noch eine Zeitangabe.

**Comment by alexsee** [comment]
@linuxcrash Kannst du mir kurz sagen, ob überhaupt keine Anzeige auftaucht. Normalerweise sollte das Statusfenster angezeigt werden, dass zumindest über die Aktion informiert. Oder meinst du "nur" den detaillierten Status der Löschung?
