### ISSUE TITLE
BSH 3.5.4 Beta2: Crash beim gleichzeitigen löschen von Backups and rekonfiguration des Backups

### ISSUE THREAD

**Issue by linuxcrash** [alexsee/bsh3#20]
Wenn man im BSH Backupbrowser mehrere Backups am löschen ist und gleichzeitig den Backupjob umkonfiguriert stürzt BSH komplett ab und startet sich neu. Ich vermute, dass das gleichzeitige zugreiffen auf die Backup-DB das ganze durcheinander bringt.

**Comment by alexsee** [comment]
Behoben.

Auf die Fertigstellung sämtlicher laufender Aktionen wird nun beim Speichern der Konfiguration gewartet.
