### ISSUE TITLE
BSH 3.5.4 Beta2: Keine Backupgrössen anzeige im Backupbroswer

### ISSUE THREAD

**Issue by linuxcrash** [alexsee/bsh3#21]
Im Backupbrowser gibt es keine Anzeige des benötigten Speicherplatzes pro Backup um zu sehen, was ungefähr and Speicherkapazität verwendet wird.

**Comment by alexsee** [comment]
Die Idee finde ich gut.

**Comment by alexsee** [comment]
Unkomprimierte Datenumfanganzeige im Tooltip hinzugefügt.
