### ISSUE TITLE
BSH 3.5.4 Beta2: BSH Crash Database locked.

### ISSUE THREAD

**Issue by linuxcrash** [alexsee/bsh3#22]
Wärend dem löschen mehrerer Backups kann im Backupbrowser weiterhin herumgeklickt werden und sollte man auf die Idee kommen nochmals auf "Mehrere Backups löschen" zu klicken, stürzt BSH mit der meldung "Database locked" ab. 

Ich empfehle in der ganzen Applikation eine Prüfung einzubauen, ob schon eine Verbindung zu SQLite besteht damit diese Fehler nicht mehr passieren und BSH mind. eine entsprechende Meldung anzeigt, dass im Moment noch eine anderer Vorgang ausgeführt wird.

**Comment by alexsee** [comment]
Ich bin da gerade noch dran an der Datenbankarchitektur Änderungen vorzunehmen. In der Regel sollten hier einfach sämtliche anderen Aktionen überhaupt nicht erst durchgeführt werden.

**Comment by alexsee** [comment]
@linuxcrash Ich kann nicht bestätigen, dass man während die Löschung läuft den Backupbrowser weiterhin benutzen kann. Eventuell habe ich inzwischen schon eine Änderung hier gemacht, die sollte aber schon in Beta 2 drin sein.
