### ISSUE TITLE
Bestätigungsfeld verschwunden

### ISSUE THREAD

**Issue by judober** [alexsee/bsh3#38]
Unter Windows 10 wird im Bereich "Dateien ausschließen" der Button zum Speichern der auszuschließenden Ordner/Dateien nicht angezeigt. Die Funktion kann aber mittels "durchtabben" aktiviert werden.

**Comment by alexsee** [comment]
@judober Hast du eine spezielle DPI Einstellung für den Bildschirm?

**Comment by judober** [comment]
Die DPI-Einstellung sollte Standard sein (wüsste zumindest nicht, wo man die ändert). Die Auflösung ist 1024x768.

**Comment by alexsee** [comment]
@judober Kannst du vielleicht mal ein Screenshot machen und hier anhängen. Ich habe verschiedene Auflösungen etc. probiert, hier taucht der Button auf.

**Comment by judober** [comment]
Hier der Screenshot:
![bsh-screenshot](https://cloud.githubusercontent.com/assets/16521254/12152655/10ba994e-b4b6-11e5-9a82-7ce8a8982506.jpg)

**Comment by alexsee** [comment]
Kannst du bitte einmal die aktuellste Betaversion austesten? Dort hatte ich bereits Anpassungen am Fenster vorgenommen.

**Comment by judober** [comment]
Mit der Beta sind die Buttons aufgetaucht.
Vielen Dank!
