### ISSUE TITLE
Eingabefeld für Speicherplatz-Warnung zu schmal

### ISSUE THREAD

**Issue by kalwados** [alexsee/bsh3#53]
Konfiguration -> Weitere
Das Feld zur Eingabe der Speicherplatz-Warnung ist etwas zu schmal für fünfstellige Werte, z.B. "20480" MB:
![bsh01](https://cloud.githubusercontent.com/assets/11840444/15092487/d0fc0dd6-146b-11e6-8c3b-a8209f138f49.png)

**Comment by alexsee** [comment]
Auch hierfür Danke. Hab die Box nun deutlich vergrößert.
