### ISSUE TITLE
Schreibfehler "Errinnern"

### ISSUE THREAD

**Issue by kalwados** [alexsee/bsh3#54]
Konfiguration -> Weitere
Errinnern wenn... Da ist ein "r" zuviel. Hat ja nix mit Error zu tun :-)

![bsh02](https://cloud.githubusercontent.com/assets/11840444/15092498/0883067e-146c-11e6-8aeb-a7e1a8906ff8.png)

**Comment by alexsee** [comment]
Danke für den Hinweis.
