### ISSUE TITLE
Dialog "Pfadbegrenzung erreicht": Schalter "Details anzeigen" vergrößert das Edit-Feld nicht

### ISSUE THREAD

**Issue by kalwados** [alexsee/bsh3#55]
Beim überschreiten der max. Pfadlänge wird ein Dialog angezeigt, der die problematischen Pfade aufliste. Dieser Dialog ist zunächst relativ klein. Durch anklicken der Checkbox "Details anzeigen" wird der Dialog zwar größer, aber das Textfeld bleibt in seiner Größe unverändert.
Erwartetes Verhalten:
Beim vergrößern des Dialogs wird das Textfeld ebenfalls größer.
![bsh03](https://cloud.githubusercontent.com/assets/11840444/15092722/858f3a56-1472-11e6-91d2-6d5426c84956.png)

**Comment by alexsee** [comment]
Da ist beim Layout wohl einiges schief gelaufen. Ist in der nächsten Version auch behoben.
