### ISSUE TITLE
Verbesserungsvorschlag: kleine Dateien nicht komprimieren

### ISSUE THREAD

**Issue by C4rsten** [alexsee/bsh3#69]
Wenn eine Datei kleiner als 1 Cluster ist, also üblicherweise 4 KB, dann kann durch das Komprimieren effektiv kein Platz eingespart werden.

Das Backup könnte daher ohne Nachteile beschleunigt werden, wenn kleine Dateien nicht komprimiert würden.

**Comment by alexsee** [comment]
Implementiert.
