### ISSUE TITLE
Ordner/ Dateityp von Sicherung ausschließen funktioniert nicht

### ISSUE THREAD

**Issue by jpwieseth** [alexsee/bsh3#82]
Hallo Alex,

in der aktuellen Betaversion V 3.6.7.4 funktioniert das ausschließen von Ordnern bzw. Dateitypen bei der Sicherung nicht.

Ich lege dir zwei Screenshoot bei.

LG
Josef

<img width="816" alt="Service BackupServicehome Ignore-Liste" src="https://user-images.githubusercontent.com/72105548/94613379-ce105100-02a4-11eb-84e6-bd1d60a21bdf.PNG">

<img width="778" alt="Service Backuphome Problem" src="https://user-images.githubusercontent.com/72105548/94613197-838ed480-02a4-11eb-9c55-2fe0a34c3496.PNG">

**Comment by alexsee** [comment]
Hallo Josef,
danke für den Hinweis. Der Fehler sollte bei der nächsten Betaversion behoben sein.
Viele Grüße
Alex
