### ISSUE TITLE
Im Backupbrowser wird der Pfad nicht markiert, in dem sich ein Backup befindet

### ISSUE THREAD

**Issue by jpwieseth** [alexsee/bsh3#83]
Hallo Alex,
wenn die Checkbox im Backupbrowser "Nur Dateien dieser Sicherung" aktiviert ist, wird der Rootpfad nicht markiert, in dem sich Backupdatein befinden.
Sie Screenshoots.

LG
Josef 

![Screenshot 2020-10-12 204459](https://user-images.githubusercontent.com/72105548/95780709-a968a000-0ccc-11eb-9a5a-af931b44a65f.jpg)
![Screenshot 2020-10-12 204642](https://user-images.githubusercontent.com/72105548/95780731-b38a9e80-0ccc-11eb-946b-b230fb0dfea7.jpg)
![Screenshot 2020-10-12 204728](https://user-images.githubusercontent.com/72105548/95780756-beddca00-0ccc-11eb-9bcb-23952f625111.jpg)
![Screenshot 2020-10-12 204804](https://user-images.githubusercontent.com/72105548/95780766-c7ce9b80-0ccc-11eb-9b66-a0af6b5680db.jpg)

**Comment by alexsee** [comment]
Behoben
