### ISSUE TITLE
Statusfenster, zu klein

### ISSUE THREAD

**Issue by jpwieseth** [alexsee/bsh3#84]
Hallo Alex,

das Statusfenster für die  Update-Meldung könnte etwas größer sein. Hab einen 4k Monitor.

LG
Josef

![Screenshot 2020-10-19 162037](https://user-images.githubusercontent.com/72105548/96464012-9eab8f00-1227-11eb-8898-1ba455a6e801.jpg)

**Comment by alexsee** [comment]
Hallo Josef,

ja, das Problem habe ich auch. Lässt sich aber nicht beheben, da die Aktualisierung eine externe Komponente ist :(
Eventuell muss ich dafür die Akualisierungsfunktion ersetzen.

Viele Grüße
Alex
